step (e,n,d) ('E':v) = (e + read v, n, d)
step (e,n,d) ('N':v) = (e, n + read v, d)
step (e,n,d) ('W':v) = (e - read v, n, d)
step (e,n,d) ('S':v) = (e, n - read v, d)
step (e,n,'E') ('F':v) = (e + read v, n, 'E')
step (e,n,'N') ('F':v) = (e, n + read v, 'N')
step (e,n,'W') ('F':v) = (e - read v, n, 'W')
step (e,n,'S') ('F':v) = (e, n - read v, 'S')
step (e,n,'E') "L90" = (e,n,'N')
step (e,n,'N') "L90" = (e,n,'W')
step (e,n,'W') "L90" = (e,n,'S')
step (e,n,'S') "L90" = (e,n,'E')
step (e,n,'E') "R90" = (e,n,'S')
step (e,n,'N') "R90" = (e,n,'E')
step (e,n,'W') "R90" = (e,n,'N')
step (e,n,'S') "R90" = (e,n,'W')
step (e,n,'E') (_:"180") = (e,n,'W')
step (e,n,'N') (_:"180") = (e,n,'S')
step (e,n,'W') (_:"180") = (e,n,'E')
step (e,n,'S') (_:"180") = (e,n,'N')
step (e,n,'E') "L270" = (e,n,'S')
step (e,n,'N') "L270" = (e,n,'E')
step (e,n,'W') "L270" = (e,n,'N')
step (e,n,'S') "L270" = (e,n,'W')
step (e,n,'E') "R270" = (e,n,'N')
step (e,n,'N') "R270" = (e,n,'W')
step (e,n,'W') "R270" = (e,n,'S')
step (e,n,'S') "R270" = (e,n,'E')
main = do
  txt <- readFile "input12.txt"
  let (e,n,_) = foldl step (0,0,'E') $ lines txt
  print (e,n,abs(e)+abs(n))

